[webservers]

web-1   ansible_host=89.169.141.207 fqdn=web-1-ru-central1-a.internal
web-2   ansible_host=89.169.140.197 fqdn=web-2-ru-central1-a.internal

[databases]

main   ansible_host=89.169.155.126 fqdn=main-db.ru-central1.internal
replica   ansible_host=89.169.136.45 fqdn=replica-db.ru-central1.internal

[storages]

storage   ansible_host=51.250.78.168 fqdn=storage.ru-central1.internal