[webservers]

web-1   ansible_host=84.252.128.129 fqdn=web-1-ru-central1-a.internal
web-2   ansible_host=84.201.157.168 fqdn=web-2-ru-central1-a.internal

[databases]

main   ansible_host=84.252.129.23 fqdn=main-db.ru-central1.internal
replica   ansible_host=89.169.154.208 fqdn=replica-db.ru-central1.internal

[storages]

storage   ansible_host=62.84.125.235 fqdn=storage.ru-central1.internal